-- ============================================================
-- Navi Borrow-Safe — SQL Analysis Queries
-- ============================================================
-- Database: Neon Postgres (drizzle-orm schema)
--
-- Data sources:
--   reviews            → Play Store reviews (Navi, MoneyView, Fibe)
--   rejection_profiles → SYNTHETIC — generated by scripts/seed.ts
--   loan_simulations   → SYNTHETIC — generated by scripts/seed.ts
--
-- All loan/profile data is CLEARLY LABELLED SYNTHETIC.
-- Never presented as real Navi operational data.
-- ============================================================

-- ──────────────────────────────────────────────────────────────────────────────
-- QUERY 1: Which funnel stage generates the most complaints?
-- Business question: Where in the loan journey are users most frustrated?
-- This motivates the entire project — rejection is the top pain point.
-- ──────────────────────────────────────────────────────────────────────────────
SELECT
  COALESCE(funnel_stage_label, 'unlabelled') AS funnel_stage_label,
  COUNT(*)                                   AS complaints,
  ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 1) AS pct
FROM reviews
WHERE sentiment = 'negative'
GROUP BY funnel_stage_label
ORDER BY complaints DESC;

/*
Expected finding: Rejection stage leads at ~30-35% of negative reviews.
Product decision: This validates building Borrow-Safe at the rejection touchpoint.
*/


-- ──────────────────────────────────────────────────────────────────────────────
-- QUERY 2: How does Navi's rejection complaint share compare to competitors?
-- Business question: Is Navi's rejection UX problem proportionally larger than
--                   MoneyView and Fibe? Benchmarks the gap.
-- ──────────────────────────────────────────────────────────────────────────────
SELECT
  source_app,
  COUNT(*)                                                                AS total_reviews,
  SUM(CASE WHEN complaint_category = 'rejection' THEN 1 ELSE 0 END)      AS rejection_complaints,
  ROUND(
    100.0 * SUM(CASE WHEN complaint_category = 'rejection' THEN 1 ELSE 0 END)
    / COUNT(*), 1
  )                                                                        AS pct_rejection_complaints
FROM reviews
GROUP BY source_app
ORDER BY pct_rejection_complaints DESC;

/*
Expected finding: All apps have rejection complaints, but the share varies.
Product decision: If Navi's share is highest, it's a strong motivation for investment.
*/


-- ──────────────────────────────────────────────────────────────────────────────
-- QUERY 3: Distribution of primary rejection reasons
-- Business question: Which fixable segment is largest? Where do we focus first?
-- Data: SYNTHETIC rejection_profiles
-- ──────────────────────────────────────────────────────────────────────────────
SELECT
  primary_reason,
  COUNT(*)                               AS users,
  ROUND(AVG(foir_calculated)::numeric, 2) AS avg_foir,
  ROUND(AVG(monthly_income))             AS avg_income_inr
FROM rejection_profiles
GROUP BY primary_reason
ORDER BY users DESC;

/*
Expected finding: foir_high and score_low are the top two reasons.
Product decision: Action plan templates prioritise these two; foir_high is fixable
in 60-90 days (close one loan), score_low takes 90+ days.
Note: Data is synthetic with realistic distributions. Real Navi data would refine this.
*/


-- ──────────────────────────────────────────────────────────────────────────────
-- QUERY 4: What share of simulated approvals fall OUTSIDE the safe-EMI band?
-- Business question: How many users would over-borrow without the simulator?
--                   This is the IPO-relevant asset-quality question.
-- Data: SYNTHETIC loan_simulations joined to rejection_profiles
-- ──────────────────────────────────────────────────────────────────────────────
SELECT
  rp.credit_score_bucket,
  COUNT(*)::int                                                              AS approvals,
  SUM(CASE WHEN ls.computed_emi > ls.safe_emi_max THEN 1 ELSE 0 END)::int  AS over_borrowing,
  ROUND(
    100.0 * SUM(CASE WHEN ls.computed_emi > ls.safe_emi_max THEN 1 ELSE 0 END)
    / COUNT(*), 1
  )                                                                          AS pct_over_band
FROM loan_simulations ls
JOIN rejection_profiles rp ON rp.id = ls.profile_id
GROUP BY rp.credit_score_bucket
ORDER BY pct_over_band DESC;

/*
Expected finding: Fair/poor score buckets have higher over-borrowing rates.
Product implication: The simulator's safe-band nudge has the highest impact on
exactly the users most likely to default — a growth + asset quality double win.
*/


-- ──────────────────────────────────────────────────────────────────────────────
-- QUERY 5: Does following the plan actually move the risk band?
-- Business question: Prove that the product creates measurable improvement.
--                   Shows the "before plan → after plan" band shift.
-- Data: SYNTHETIC loan_simulations
-- ──────────────────────────────────────────────────────────────────────────────
SELECT
  risk_band_before,
  risk_band_after,
  COUNT(*)::int                                                              AS users,
  ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 1)                        AS pct
FROM loan_simulations
GROUP BY risk_band_before, risk_band_after
ORDER BY users DESC;

/*
Expected finding: Many users who start at high/medium risk move to lower bands
after completing the plan and choosing a safer loan amount.
Product implication: The north-star metric (Safe-Approved Reactivations) is
measurable from this table in production.
*/


-- ──────────────────────────────────────────────────────────────────────────────
-- QUERY 6: EMI Shield impact — among high-risk simulations, how many benefit?
-- Business question: Validate that the cross-sell is genuinely helpful
--                   (vs. mis-selling to users who don't need it).
-- Data: SYNTHETIC loan_simulations
-- ──────────────────────────────────────────────────────────────────────────────
SELECT
  COUNT(*)::int                                                                AS high_risk_users,
  SUM(CASE WHEN shield_recommended_bool THEN 1 ELSE 0 END)::int               AS shield_helps,
  ROUND(
    100.0 * SUM(CASE WHEN shield_recommended_bool THEN 1 ELSE 0 END)
    / COUNT(*), 1
  )                                                                            AS pct_shield_helps
FROM loan_simulations
WHERE risk_band_after = 'high';

/*
Expected finding: 100% of high-risk users have shield_recommended = true
(by definition — Shield is shown only to medium|high risk users).
Business implication: Every high-risk borrower gets an honest safety net offer.
The attach rate on this cohort is the insurance revenue lever.
*/


-- ──────────────────────────────────────────────────────────────────────────────
-- BONUS QUERY 7: Monthly simulation volume trend
-- Business question: Are more users engaging with the safe-borrowing tool
--                   over time? (Growth metric for the product itself)
-- ──────────────────────────────────────────────────────────────────────────────
SELECT
  DATE_TRUNC('month', created_at)::date AS month,
  COUNT(*)::int                          AS simulations,
  ROUND(AVG(post_loan_foir)::numeric, 1) AS avg_post_loan_foir,
  SUM(CASE WHEN stress_pass_bool THEN 1 ELSE 0 END)::int AS stress_pass_count
FROM loan_simulations
GROUP BY month
ORDER BY month;


-- ──────────────────────────────────────────────────────────────────────────────
-- BONUS QUERY 8: Top complaint categories by app and sentiment
-- Business question: Beyond rejection, what's the next biggest complaint cluster?
--                   Informs the product roadmap beyond Borrow-Safe.
-- ──────────────────────────────────────────────────────────────────────────────
SELECT
  source_app,
  complaint_category,
  sentiment,
  COUNT(*)::int AS count,
  ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (PARTITION BY source_app), 1) AS pct_of_app
FROM reviews
WHERE sentiment = 'negative'
GROUP BY source_app, complaint_category, sentiment
ORDER BY source_app, count DESC;
